### ISSUE TITLE
Could you figure out v1 and v2 differences?

### ISSUE THREAD

**Issue by a-x-** [enb-make/enb-stylus#106]
Are you have list of deletions, renames and deprecations in API?

And, is v2-rc production ready you feel?

**Comment by a-x-** [comment]
inspired by followed issues:
#105
stylus/stylus#1977

**Comment by blond** [comment]
@a-x- Hi!

You can see list of differences in [changelog](https://github.com/enb-make/enb-stylus/blob/master/CHANGELOG.md).

Now you can try to upgrade to `v2.0.0-rc2` version. Stable version  will be released in coming days.

**Comment by a-x-** [comment]
Hey, @blond!
Thank you!

**Comment by blond** [comment]
:tada: Release `v2.0.0`!

**Comment by a-x-** [comment]
Yeah!!
