### ISSUE TITLE
Баг с # в урлах

### ISSUE THREAD

**Issue by Aetet** [enb-make/enb-stylus#21]
При сборке с помощью таски enb-stylus/tech/css-stylus, если в файле .styl есть такая конструкция:
body
  background: url("#")

Падает ошибка:
TypeError: /Test/stylus-test/static/desktop.blocks/b-page/b-page.styl:2 1| body > 2| background: url("#") 3| Cannot call method 'substr' of null at "body"

Ошибка происходит внутри stylus, который использует enb-stylus.

Если собирать последним stylus 0.49.3, тот файл с таким же содержимым:
body
  background: url("#")
То никаких проблем нет и конструкция отрабатывает корректно.

Дело в том, что enb-stylus использует устаревшую версию stylus: 0.47.1
Тогда, как актуальная версию stylus: 0.49.3.

Прошу починить и поднять версию stylus для фикса бага.

**Comment by rakchaev** [comment]
Зарелижено в stylus@0.50.0.

**Comment by andrewblond** [comment]
Исправлено в `v1.2.2`.
