### ISSUE TITLE
Не склеивает styl файлы с разных уровней переопределения

### ISSUE THREAD

**Issue by tavriaforever** [enb-make/enb-stylus#26]
@andrewblond 
Версия пакета 1.2.0 
Обновленный пакет перестал склеивать с разных уровней одинаковые файлы.
Например, в bem-site-engine есть файл menu_list.styl
Если на уровне лего-сайта есть этот файл с доопределением стилей, то он не доезжает.

Все ок -> в  1.1.5

**Comment by alsun** [comment]
+1
Склеивает 2 раза файл с верхнего уровня.
При склейке css с уровня проекта оказывается выше, чем styl с уровня common =(

**Comment by andrewblond** [comment]
Не смог воспроизвести баг. Ещё актуально?

> При склейке css с уровня проекта оказывается выше, чем styl с уровня common =(

Это другая проблема, про неё надо думать не в рамках этого ишьюса.

**Comment by andrewblond** [comment]
> При склейке css с уровня проекта оказывается выше, чем styl с уровня common =(

Завели ишью https://github.com/enb-make/enb-stylus/issues/47

**Comment by andrewblond** [comment]
@alsun @tavriaforever ping!?

**Comment by tavriaforever** [comment]
Кажется, что задача сильно устарела, воспроизвести уже у меня самого не получилось. Версия enb `0.15.0` и версия пакет `1.2.3` – все работает ок. Закрываем?

**Comment by blond** [comment]
Оказалось, что это баг в самом `stylus` — https://github.com/stylus/stylus/issues/1951

**Comment by blond** [comment]
@tavriaforever нужно обновить `stylus` до `0.52.0` — #90.

**Comment by blond** [comment]
Fixed in #91
