### ISSUE TITLE
Invalid styl file forces enb server to not responde

### ISSUE THREAD

**Issue by zxqfox** [enb-make/enb-stylus#29]
How to repeat:

With a project-stub (or yo bem-stub) make a common.blocks/page/page.styl with mixed tabs and spaces as indent.
Force to render page
Result: Timeout + error mess in stderr?;
Expected result: Stack trace in the response + error mess in stderr.

Ref: https://github.com/enb-make/enb/issues/211

**upd** See also: http://stackoverflow.com/questions/18677442/i-get-eos-error-with-stylus-when-compiling-with-grunt-contrib-stylus

**Comment by tavriaforever** [comment]
- `enb` 0.16
- `enb-stylus`#master
- `styl` file
```stylus
.icon
	width: 200px
	height: 200px
  border: 2px solid #fc0
```
**command line**
```
enb server
open -a Yandex localhost:8080/desktop.bundles/index/index.html
```
**Result:**
![2015-07-23 17-52-40 1 tavria tavria-osx sites proj-stub-enb-stylus](https://cloud.githubusercontent.com/assets/975906/8853581/fa188988-3163-11e5-844f-29f3ee3cf089.png)

Bug was`t reproduced.
