### ISSUE TITLE
css and styl should be concatenated in proper order

### ISSUE THREAD

**Issue by tadatuta** [enb-make/enb-stylus#47]
Now when there are `*.css` and `*.styl` on the same project, `enb-stylus` merge them one after another and doesn't respect proper order.

**Comment by tavriaforever** [comment]
@tadatuta @blond If this https://github.com/enb-bem/enb-bem-techs/issues/156 fix your problem, I think – yes. Can I close this issue?
You can check order here https://github.com/tavriaforever/proj-stub-enb-stylus/commit/61419a90643935170882d4fbace74e3377acbba6
output results: https://gist.github.com/tavriaforever/ca035cb3b7f19780a3f5

**Comment by tadatuta** [comment]
Fixed at https://github.com/enb-bem/enb-bem-techs/issues/156
