### ISSUE TITLE
Variables option

### ISSUE THREAD

**Issue by blond** [enb-make/enb-stylus#53]
Array of variables to [define](https://github.com/stylus/stylus/blob/master/docs/js.md#definename-fn).

See [docs](https://github.com/stylus/stylus/blob/master/docs/variables.md).

**Comment by tavriaforever** [comment]
Decided not to do due to the fact that the option has always existed, but didn't work and no one complained. If you find that someone has used it (BUT HOW?) – then we will think over how to do it better.
