### ISSUE TITLE
Comments options

### ISSUE THREAD

**Issue by blond** [enb-make/enb-stylus#55]
* [x] `comments: true` — Default value. Emits comments in the generated CSS indicating the url. Need use ENB-style: `/* <url>:begin */\n<code>\n/* <url>:end */`.
* [x] `comments: false` — Disables emits comments.
* [ ] `comments: 'line-numbers` — Emits comments in the generated CSS indicating the corresponding Stylus line.

**Comment by tavriaforever** [comment]
What you mean in this items?
> `comments: 'line-numbers` — Emits comments in the generated CSS indicating the corresponding Stylus line.

**Comment by blond** [comment]
@tavriaforever https://github.com/stylus/stylus/blob/master/bin/stylus#L175

**Comment by blond** [comment]
Fixed in #61
