### ISSUE TITLE
Use `clean-css` for `compress`

### ISSUE THREAD

**Issue by blond** [enb-make/enb-stylus#71]
* [ ] Use `clean-css` for `compress` by default: `compress: true`.
* [ ] <del>Support native compressor: `compress: 'native'`.</del>

**Comment by tavriaforever** [comment]
After discussion, decided not to use the native `stylus` compressor, because he minified only `.styl` files and `css` remains as is because it not open this `@import`. 
Decided to do this after rendering using `clean-css`
