### ISSUE TITLE
Неверный путь на изображения

### ISSUE THREAD

**Issue by aliosv** [enb-make/enb-stylus#72]
Урлы из css не резолвятся относительно ноды, в которую собираются, т.е. остаются как есть. Тест кейс https://github.com/aliosv/proj-stub-enb-stylus/commit/190f9a5bfe8e66e5be7bcf6f5520df9108e9ed76
при смене расширения на styl, файл не попадает в сборку о_О

**Comment by blond** [comment]
Спасибо за реквест, исправим!

**Comment by levonet** [comment]
\сс @tavriaforever

**Comment by tavriaforever** [comment]
Fixed in https://github.com/enb-make/enb-stylus/pull/61
Will be in new `v2.0.0` version.

also work with alpha version https://github.com/enb-make/enb-stylus/releases/tag/v2.0.0-alpha4
